# Generated by Django 5.0.2 on 2025-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('headers', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
